[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Lint
deny_warnings = true

# Solc options
solc = '0.8.27'
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200000

# EVM options
gas_limit = 30000000
gas_price = 1
block_base_fee_per_gas = 0
block_gas_limit = 30000000

# Fuzz tests options
[fuzz]
# Reduce the numbers of runs if fuzz tests takes too long in your machine.
runs = 2500